# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nest/trait/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15nest/trait/user.proto\x12\x0fnest.trait.user\x1a\x19google/protobuf/any.proto\"3\n\rUserInfoTrait\x12\x11\n\tlegacy_id\x18\x01 \x01(\t\x12\x0f\n\x07unknown\x18\x02 \x01(\x05\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nest.trait.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFOTRAIT._serialized_start=69
  _USERINFOTRAIT._serialized_end=120
  _STRING_INDIRECT._serialized_start=122
  _STRING_INDIRECT._serialized_end=154
  _FLOAT_INDIRECT._serialized_start=156
  _FLOAT_INDIRECT._serialized_end=187
  _INT32_INDIRECT._serialized_start=189
  _INT32_INDIRECT._serialized_end=220
# @@protoc_insertion_point(module_scope)
