# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weave/trait/description.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dweave/trait/description.proto\x12\x17weave.trait.description\x1a\x19google/protobuf/any.proto\"\xbe\x01\n\x13\x44\x65viceIdentityTrait\x12>\n\x0cmanufacturer\x18\x02 \x01(\x0b\x32(.weave.trait.description.String_Indirect\x12<\n\nmodel_name\x18\x04 \x01(\x0b\x32(.weave.trait.description.String_Indirect\x12\x15\n\rserial_number\x18\x06 \x01(\t\x12\x12\n\nfw_version\x18\x07 \x01(\t\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weave.trait.description_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICEIDENTITYTRAIT._serialized_start=86
  _DEVICEIDENTITYTRAIT._serialized_end=276
  _STRING_INDIRECT._serialized_start=278
  _STRING_INDIRECT._serialized_end=310
  _FLOAT_INDIRECT._serialized_start=312
  _FLOAT_INDIRECT._serialized_end=343
  _INT32_INDIRECT._serialized_start=345
  _INT32_INDIRECT._serialized_end=376
# @@protoc_insertion_point(module_scope)
