# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nest/trait/structure.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anest/trait/structure.proto\x12\x14nest.trait.structure\x1a\x19google/protobuf/any.proto\"\'\n\x12StructureInfoTrait\x12\x11\n\tlegacy_id\x18\x01 \x01(\t\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nest.trait.structure_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRUCTUREINFOTRAIT._serialized_start=79
  _STRUCTUREINFOTRAIT._serialized_end=118
  _STRING_INDIRECT._serialized_start=120
  _STRING_INDIRECT._serialized_end=152
  _FLOAT_INDIRECT._serialized_start=154
  _FLOAT_INDIRECT._serialized_end=185
  _INT32_INDIRECT._serialized_start=187
  _INT32_INDIRECT._serialized_end=218
# @@protoc_insertion_point(module_scope)
