# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: root.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
  2,
    '',
    'root.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .nest.trait import hvac_pb2 as nest_dot_trait_dot_hvac__pb2
from .nest.trait import sensor_pb2 as nest_dot_trait_dot_sensor__pb2
from .nest.trait import structure_pb2 as nest_dot_trait_dot_structure__pb2
from .weave.trait import peerdevices_pb2 as weave_dot_trait_dot_peerdevices__pb2
from .nest.trait import located_pb2 as nest_dot_trait_dot_located__pb2
from .weave.trait import description_pb2 as weave_dot_trait_dot_description__pb2
from .nest.trait import user_pb2 as nest_dot_trait_dot_user__pb2
from .weave.trait import heartbeat_pb2 as weave_dot_trait_dot_heartbeat__pb2
from .weave import common_pb2 as weave_dot_common__pb2
from .weave.trait import security_pb2 as weave_dot_trait_dot_security__pb2
from .weave.trait import power_pb2 as weave_dot_trait_dot_power__pb2
from .nest.trait import security_pb2 as nest_dot_trait_dot_security__pb2
from .nest.trait import detector_pb2 as nest_dot_trait_dot_detector__pb2
from .nest import messages_pb2 as nest_dot_messages__pb2
from .nestlabs.gateway import v1_pb2 as nestlabs_dot_gateway_dot_v1__pb2
from .nest import rpc_pb2 as nest_dot_rpc__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroot.proto\x12\x08nest.rpc\x1a\x15nest/trait/hvac.proto\x1a\x17nest/trait/sensor.proto\x1a\x1anest/trait/structure.proto\x1a\x1dweave/trait/peerdevices.proto\x1a\x18nest/trait/located.proto\x1a\x1dweave/trait/description.proto\x1a\x15nest/trait/user.proto\x1a\x1bweave/trait/heartbeat.proto\x1a\x12weave/common.proto\x1a\x1aweave/trait/security.proto\x1a\x17weave/trait/power.proto\x1a\x19nest/trait/security.proto\x1a\x19nest/trait/detector.proto\x1a\x13nest/messages.proto\x1a\x19nestlabs/gateway/v1.proto\x1a\x0enest/rpc.proto\x1a\x19google/protobuf/any.proto\"5\n\x0cObjectIdPair\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\">\n\x14\x44ynamicProp_Indirect\x12&\n\x08property\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"h\n\x10TraitGetProperty\x12&\n\x06object\x18\x01 \x01(\x0b\x32\x16.nest.rpc.ObjectIdPair\x12,\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1e.nest.rpc.DynamicProp_Indirect\"b\n\x10TraitSetProperty\x12&\n\x06object\x18\x01 \x01(\x0b\x32\x16.nest.rpc.ObjectIdPair\x12&\n\x08property\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"_\n\x0bNestMessage\x12\'\n\x03set\x18\x01 \x03(\x0b\x32\x1a.nest.rpc.TraitSetProperty\x12\'\n\x03get\x18\x03 \x03(\x0b\x32\x1a.nest.rpc.TraitGetProperty\"d\n\nStreamBody\x12&\n\x07message\x18\x01 \x03(\x0b\x32\x15.nest.rpc.NestMessage\x12 \n\x06status\x18\x02 \x01(\x0b\x32\x10.nest.rpc.Status\x12\x0c\n\x04noop\x18\x0f \x03(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'root_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTIDPAIR']._serialized_start=458
  _globals['_OBJECTIDPAIR']._serialized_end=511
  _globals['_DYNAMICPROP_INDIRECT']._serialized_start=513
  _globals['_DYNAMICPROP_INDIRECT']._serialized_end=575
  _globals['_TRAITGETPROPERTY']._serialized_start=577
  _globals['_TRAITGETPROPERTY']._serialized_end=681
  _globals['_TRAITSETPROPERTY']._serialized_start=683
  _globals['_TRAITSETPROPERTY']._serialized_end=781
  _globals['_NESTMESSAGE']._serialized_start=783
  _globals['_NESTMESSAGE']._serialized_end=878
  _globals['_STREAMBODY']._serialized_start=880
  _globals['_STREAMBODY']._serialized_end=980
# @@protoc_insertion_point(module_scope)
