# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nest/trait/sensor.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
  2,
    '',
    'nest/trait/sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17nest/trait/sensor.proto\x12\x11nest.trait.sensor\x1a\x19google/protobuf/any.proto\"~\n\rHumidityTrait\x12\x35\n\x08humidity\x18\x01 \x01(\x0b\x32#.nest.trait.sensor.HumidityTrait.X1\x1a\x36\n\x02X1\x12\x30\n\x05value\x18\x01 \x01(\x0b\x32!.nest.trait.sensor.Float_Indirect\"\x87\x01\n\x10TemperatureTrait\x12;\n\x0btemperature\x18\x01 \x01(\x0b\x32&.nest.trait.sensor.TemperatureTrait.X1\x1a\x36\n\x02X1\x12\x30\n\x05value\x18\x01 \x01(\x0b\x32!.nest.trait.sensor.Float_Indirect\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nest.trait.sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HUMIDITYTRAIT']._serialized_start=73
  _globals['_HUMIDITYTRAIT']._serialized_end=199
  _globals['_HUMIDITYTRAIT_X1']._serialized_start=145
  _globals['_HUMIDITYTRAIT_X1']._serialized_end=199
  _globals['_TEMPERATURETRAIT']._serialized_start=202
  _globals['_TEMPERATURETRAIT']._serialized_end=337
  _globals['_TEMPERATURETRAIT_X1']._serialized_start=145
  _globals['_TEMPERATURETRAIT_X1']._serialized_end=199
  _globals['_STRING_INDIRECT']._serialized_start=339
  _globals['_STRING_INDIRECT']._serialized_end=371
  _globals['_FLOAT_INDIRECT']._serialized_start=373
  _globals['_FLOAT_INDIRECT']._serialized_end=404
  _globals['_INT32_INDIRECT']._serialized_start=406
  _globals['_INT32_INDIRECT']._serialized_end=437
# @@protoc_insertion_point(module_scope)
